version: "4.3"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres_gestaoint
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: Senha123@
      POSTGRES_DB: gestao
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U joao -d gestao"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - proxy_network

volumes:  
  postgres_data:

networks:
  proxy_network:
    external: true
