version: "3.8"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://joao:Senha123%40@db:5432/gestao
      REDIS_URL: redis://redis_db:6379
    depends_on:
      - db
      - redis
    networks:
      - app_net

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: Senha123@
      POSTGRES_DB: gestao
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  db-data:
