version: "3.8"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: Senha123@
      POSTGRES_DB: gestao
    ports:
      - 5433:5432  # Porta do PostgreSQL

volumes:
  db-data:
